---
# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: Bjorn Detector Community Support
    url: https://github.com/infinition/bjorn-detector/discussions
    about: Please ask and answer questions here.
  - name: Bjorn Detector Security Reports
    url: https://infinition.github.io/bjorn-detector/SECURITY
    about: Please report security vulnerabilities here.
