---
# .github/workflows/stale.yml

name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '23 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Mmm, I ll save this one, but no important at moment, thanks!'
        stale-pr-message: 'Looks like gods abandoned us... Damn!'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
